CREATE DATABASE DB_ECOMMERCESERVICES;

USE DB_ECOMMERCESERVICES;

CREATE TABLE TB_PRODUTOS(
ID INT AUTO_INCREMENT,
DESCRICAO VARCHAR(255),
ESTOQUE INT,
CATEGORIA VARCHAR(255),
PRECO DECIMAL(10,2),
PRIMARY KEY(ID)
);

SELECT * FROM TB_PRODUTOS;
DROP TABLE TB_PRODUTOS; -- exclui tabela inteira até os atributos e registros
INSERT INTO TB_PRODUTOS(DESCRICAO,ESTOQUE,CATEGORIA,PRECO) VALUES
("PANELA ELÉTRICA",5,"ELETRODOMESTICO",1500),
("ASPIRADOR DE PÓ",5,"ELETRODOMESTICO",3500),
("CELULAR ",20,"ELETROELETRONICO",1900),
("NOTEBOOK",8,"ELETROELETRONICO",3500),
("FONE DE OUVIDO SEM FIO",20,"ELETROELETRONICO",150),
("BATEDEIRA",7,"ELETRODOMESTICO",2500),
("SECADOR DE CABELO",8,"ELETRODOMESTICO",1200),
("EDREDON",10,"CAMA MESA E BANHO",400);

SELECT * FROM  TB_PRODUTOS WHERE PRECO >= 500;
SELECT * FROM  TB_PRODUTOS WHERE PRECO <= 500;

-- Trabalhando com update
UPDATE TB_PRODUTOS SET PRECO = 1200 WHERE ID = 1;
UPDATE TB_PRODUTOS SET PRECO = 1500 WHERE ID = 2;
UPDATE TB_PRODUTOS SET PRECO = 1000 WHERE ID = 6;

SELECT * FROM TB_PRODUTOS;