CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255),
DESCRICAO VARCHAR(255),
primary key(ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
MARCA VARCHAR(255),
INFO_ADD VARCHAR(255),
PRECO DECIMAL(10,2),
CATEGORIAS_ID BIGINT,

PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);
-- REMOVER
DROP TABLE TB_CATEGORIAS;
DROP TABLE TB_PRODUTOS;

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS(TIPO,DESCRICAO) VALUES 
("MEDICAMENTOS", "COM RECEITA E/OU TRATAMENTO EM CASA"),("VIDA SAUDÁVEL","FITOTERÁPICOS,PRE OU POS TREINO"),
("MAMÃE E BEBÊ", "FRALDAS, ACESSÓRIOS E LEITES"),("COSMÉTICOS","PRODUTOS, ACESSÓRIOS E TINTURAS"),
("HIGIENE PESSOAL","DESODORANTE, BUCAL E CUIDADOS ÍNTIMOS");

INSERT INTO TB_PRODUTOS(NOME,MARCA,INFO_ADD,PRECO,CATEGORIAS_ID) 
VALUES("INALADOR COMPRESSOR","OMRON","1 UNIDADE",208.99,1),
("PARACETAMOL","EUROFARMA","36 COMPRIMIDOS",36.74,1),
("SUPLEMENTO VITAMÍNICO","MEDLEY","100 CÁPSULAS",94.99,2),
("WHEY ZERO LACTOSE","PIRACANJUBA","250ML",89.99,2),
("FRALDA DESCARTÁVEL","PAMPERS","90 TIRAS",80.90,3),
("FÓRMULA INFANTIL","NAN","800G",55.00,3),
("CREME DE PENTEAR","SEDA","300ML",13.99,4),
("DESODORANTE","DOVE","150ML",15.90,5);

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 5.00 AND 60.00;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID 
WHERE TIPO = "MEDICAMENTOS";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID 
WHERE TIPO = "MAMÃE E BEBÊ";