CREATE DATABASE db_generation_game_online;

USE db_generation_game_online;

CREATE TABLE tb_classes(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255),
DESCRICAO VARCHAR(255),
primary key(ID)
);

CREATE TABLE tb_personagens(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
FORCA INT,
ATAQUE INT,
DEFESA INT,
INTELIGENCIA INT,
CLASSES_ID BIGINT,

PRIMARY KEY (ID),
FOREIGN KEY (CLASSES_ID) REFERENCES TB_CLASSES(ID)
);

DROP TABLE TB_CLASSES;
DROP TABLE TB_PERSONAGENS;

SELECT * FROM TB_CLASSES;
SELECT * FROM TB_PERSONAGENS;

INSERT INTO TB_CLASSES(TIPO,DESCRICAO) VALUES 
("ARQUEIROS", "SOLTA FLECHAS"),("MAGOS","LANÇA FEITIÇOS"),
("JUSTICEIROS", "FAZ JUSTIÇA EM DEFESA DO REINO-MOR"),("ESPADACHINS","FAZ ATAQUE A FAVOR DO REINO-MOR");

INSERT INTO TB_PERSONAGENS(NOME,FORCA,ATAQUE,DEFESA,INTELIGENCIA,CLASSES_ID) 
VALUES("SAMYMASTER",10,700,2000,9,1),
("KATURA",9,1000,2000,5,3),
("CITARA",8,1500,1500,7,2),
("GIHARD",7,2000,2000,8,4), 
("YASHIRO",10,1500,2500,9,1),
("TAMAGUCHI",8,2000,1500,8,2),
("CHATYRHO",10,2500,3000,10,3),
("VANYSHA",8,1600,1800,10,4);

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGENS WHERE DEFESA BETWEEN 1000 AND 2000;
SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "C%";
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID;
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID 
WHERE TIPO = "ARQUEIROS";
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID 
WHERE TIPO = "MAGOS";