CREATE DATABASE db_pizzaria_legal;
USE db_pizzaria_legal;

CREATE TABLE tb_categorias(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255),
DESCRICAO VARCHAR(255),
primary key(ID)
);

CREATE TABLE tb_pizzas(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
SABOR_PRINCIPAL VARCHAR(255),
COMPLEMENTOS VARCHAR(255),
PRECO INT,
CATEGORIAS_ID BIGINT,

PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);
-- REMOVER
DROP TABLE TB_CATEGORIAS;
DROP TABLE TB_PIZZAS;

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PIZZAS;

INSERT INTO TB_CATEGORIAS(TIPO,DESCRICAO) VALUES 
("DOCE", "A MAIS PEDIDAS"),("SALGADA","PRODUTOS DE ÓTIMA QUALIDADE"),
("VEGETARIANA", "PARA QUEM AMA A NATUREZA"),("TRADICIONAL","SABORES MAIS PEDIDOS"),
("ESPECIAIS","REQUINTE NO SABOR");

INSERT INTO TB_PIZZAS(NOME,SABOR_PRINCIPAL,COMPLEMENTOS,PRECO,CATEGORIAS_ID) 
VALUES("MARGUERITA","MUSSARELA","MANJERICÃO E TOMATE",40.00,4),
("TOSCANA","CALABRESA","MUSSARELA, CEBOLA E TOMATE",45.00,4),
("AMOR PERFEITO","MORANGO","CHOCOLATE E GRANULADO",55.00,1),
("ROMEU E JULIETA","GOIABADA","MUSSARELA",55.00,1),
("PORTUGUESA","PRESUNTO","MUSSARELA, OVOS, CEBOLA, MILHO, BACON E ERVILHA",60.00,2),
("PERUANA","ATUM","MUSSARELA",55.00,2),
("ESCAROLA","ESCAROLA","MUSSARELA E BACON",50.00,3),
("PEPERONI","PEPERONI","MUSSARELA E ALHO FRITO",55.00,5);

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;
SELECT * FROM TB_PIZZAS WHERE PRECO BETWEEN 50.00 AND 100.00;
SELECT * FROM TB_PIZZAS WHERE NOME LIKE "M%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID 
WHERE TIPO = "DOCE";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIAS_ID = TB_CATEGORIAS.ID 
WHERE TIPO = "VEGETARIANA";