CREATE DATABASE DB_RHSERVICES;

USE DB_RHSERVICES;

CREATE TABLE TB_COLABORADORES(
ID BIGINT auto_increment,
NOME VARCHAR(1000),
IDADE INT,
FUNCAO CHAR(255),
DEPTO CHAR(255),
SEXO CHAR(255),
SALARIO FLOAT(10,2),
PRIMARY KEY(ID)
);

-- opção 1 para inserir dados na tabela:
INSERT INTO TB_COLABORADORES(NOME, IDADE, FUNCAO,DEPTO, SEXO, SALARIO)
VALUES("ELIANE",37,"DESENVOLVEDOR","TI","FEMININO",7500);
INSERT INTO TB_COLABORADORES(NOME, IDADE, FUNCAO,DEPTO, SEXO, SALARIO)
VALUES ("JOSILDO",45,"PINTOR","MANUTENÇÃO","MASCULINO",3500);
INSERT INTO TB_COLABORADORES(NOME, IDADE, FUNCAO,DEPTO, SEXO, SALARIO)
VALUES("CARLOTA",30,"COPEIRA","SERVIÇOS GERAIS","FEMININO",1900);
INSERT INTO TB_COLABORADORES(NOME, IDADE, FUNCAO,DEPTO, SEXO, SALARIO)
VALUES("EDILEUSA",35,"AUXILIAR ADM","ADMINISTRATIVO","FEMININO",2500);
INSERT INTO TB_COLABORADORES(NOME, IDADE, FUNCAO,DEPTO, SEXO, SALARIO)
VALUES("MARLUCE",25,"APRENDIZ","RH","FEMININO",1500);

-- opcao 2 para inserir dados na tabela:
INSERT INTO TB_COLABORADORES(NOME, IDADE, FUNCAO,DEPTO, SEXO, SALARIO) VALUES
("ELIANE",37,"DESENVOLVEDOR","TI","FEMININO",7500),
("JOSILDO",45,"PINTOR","MANUTENÇÃO","MASCULINO",3500),
("CARLOTA",30,"COPEIRA","SERVIÇOS GERAIS","FEMININO",1900),
("EDILEUSA",35,"AUXILIAR ADM","ADMINISTRATIVO","FEMININO",2500),
("MARLUCE",25,"APRENDIZ","RH","FEMININO",1500);

SELECT * FROM  TB_COLABORADORES;
DROP TABLE TB_COLABORADORES; -- exclui tabela inteira até os atributos e registros

SELECT * FROM  TB_COLABORADORES WHERE SALARIO >= 2000;
SELECT * FROM  TB_COLABORADORES WHERE SALARIO <= 2000;

-- Trabalhando com update
UPDATE TB_COLABORADORES SET DEPTO = "FINANCEIRO" WHERE ID = 5;
