CREATE DATABASE DB_SECRETARIAESCOLAR;

USE DB_SECRETARIAESCOLAR;

CREATE TABLE TB_ALUNOS(
ID INT AUTO_INCREMENT,
NOME VARCHAR(255),
IDADE INT,
ANO INT,
SALA INT,
MEDIA DECIMAL(10,2),
PRIMARY KEY(ID)
);

DROP TABLE TB_ALUNOS; -- exclui tabela inteira até os atributos e registros
SELECT * FROM TB_ALUNOS;

INSERT INTO TB_ALUNOS(NOME,IDADE,ANO,SALA,MEDIA)
VALUES("EMILIO",14,9,17,6.5),
("LAURA",14,9,17,6.5),
("ENZO",13,8,15,7.5),
("MATHEUS",14,9,17,6),
("NARA",13,8,15,7.5),
("LEO",14,9,17,8.5),
("MAISA",13,8,15,6.5),
("MELINDA",14,9,17,8.5);

-- Trabalhando com update
UPDATE TB_ALUNOS SET MEDIA = 7 WHERE ID = 1;
UPDATE TB_ALUNOS SET MEDIA = 9.5 WHERE ID = 6;
UPDATE TB_ALUNOS SET MEDIA = 8.5 WHERE ID = 3;