CREATE DATABASE DB_ECOMMERCESERVICES;

USE DB_ECOMMERCESERVICES;

CREATE TABLE TB_PRODUTOS(
ID INT AUTO_INCREMENT,
DESCRICAO VARCHAR(255),
QTDE INT,
EMBALAGEM VARCHAR(255),
PRECO DECIMAL(10,2),
PRIMARY KEY(ID)
);

DROP TABLE TB_PRODUTOS; -- exclui tabela inteira até os atributos e registros
INSERT INTO TB_PRODUTOS(DESCRICAO, QTDE, EMBALAGEM,PRECO) VALUES
("ELIANE",37,"DESENVOLVEDOR","TI","FEMININO",7500),
("JOSILDO",45,"PINTOR","MANUTENÇÃO","MASCULINO",3500),
("CARLOTA",30,"COPEIRA","SERVIÇOS GERAIS","FEMININO",1900),
("EDILEUSA",35,"AUXILIAR ADM","ADMINISTRATIVO","FEMININO",2500),
("MARLUCE",25,"APRENDIZ","RH","FEMININO",1500);

SELECT * FROM TB_PRODUTOS;